### ISSUE TITLE
iPhoneX bug

### ISSUE THREAD

**Issue by vortek** [aunnnn/AppStoreiOS11InteractiveTransition_old#1]
Hello, on the iphoneX the card detail view is not all the way to the top. And when closed, it jumps the same amount.

**Comment by aunnnn** [comment]
Will fix! Probably about the safe area stuff.

**Comment by aunnnn** [comment]
@vortek The iPhoneX safe area is fixed, check out the latest on master. One caveat though is that the title/detail label will be covered with the notch.

About using image from URL instead of static image, one workaround is to make sure the image is loaded and cached first before allowing the presentation to start. E.g., you can refetch image again with KingFisher on collection's didSelectItem action. If the image is already loaded and cached this should be instant. Then in the completion block you can now access the image, pass it around, doing resize and some other setup, and start the presentation.

A more complex way is to use image from URL for all of the steps, and transform the image view with the scale you need at each stage. This will take more work than the former way though.

**Comment by aunnnn** [comment]
For changes you can look at this commit https://github.com/aunnnn/AppStoreiOS11InteractiveTransition/commit/70765cb8590e4977be8078c673835f67fe0e2c95

In sum 1. I rewire constraints that pin to safe area to superview instead, 2. Set additional safe area to go under status bar in card detail page, 3. Set top anchor animation to go under status bar.
